### ISSUE TITLE
brameleiloes.com.br

### ISSUE THREAD

**Issue by scorninpc** [scorninpc/urbanmove.com.br#10]
- erro nos documentos

**Comment by scorninpc** [comment]
Acredito que de pra pegar o documento pelo `#accordion-documentos`

![image](https://github.com/scorninpc/urbanmove.com.br/assets/2607849/ef6f9901-f1b3-4baf-946a-eb2c2d87fd20)

Ficaria algo como:

`#accordion-documentos .nav-item:nth-child(1)`
`#accordion-documentos .nav-item:nth-child(2)`
`#accordion-documentos .nav-item:nth-child(3)`

**Comment by PriscillaSousa** [comment]
Boa noite. Conseguir arrumar esse, Obrigada!
