### ISSUE TITLE
Alteração de Status

### ISSUE THREAD

**Issue by Apiraja** [scorninpc/urbanmove.com.br#12]
O Leilão foi encerrado do 

https://www.hastavip.com.br/lote/imovel-terreno-res-san-diego-paysage-noble-vargem-grande-paulista-sao-paulo-608500

e o seletor abaixo não é mais válido

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/1e0f2b8f-3fc8-47a7-9427-95060c36ed86)

Agora seria o 

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/13f25a63-7f21-4ba5-bc81-92f5859f108a)

Futuramente temos que implementar essas variações, provavelmente chamando de variável status_encerrado, ou algo assim e criar as regras de utilização...

O que achei curioso é que quando pedi para atualizar no painel, retornou o "Aberto", quando cadastramos um link, ele é baixado e a atualização não é online?

**Comment by scorninpc** [comment]
Essa solução não funcionaria https://github.com/scorninpc/urbanmove.com.br/issues/8?

> O que achei curioso é que quando pedi para atualizar no painel, retornou o "Aberto", quando cadastramos um link, ele é baixado e a atualização não é online?

Não é online. Na primeira execução ele faz um cache. Assim o teste fica mais rapido, e não tem perigo do site bloquear a gente

**Comment by Apiraja** [comment]
Funcionaria sim, seria ideal ao meu ver.
É imaginei que não fosse online, só queria confirmar
