### ISSUE TITLE
medeirosleiloes.com.br

### ISSUE THREAD

**Issue by PriscillaSousa** [scorninpc/urbanmove.com.br#13]
Endereço discriminado dentro de descrição.

**Comment by Apiraja** [comment]
Link: https://www.medeirosleiloes.com.br/leilao/venda-direta-comarcas-de-curitiba-paranavai-cidade-gaucha-alto-parana-15-06-2023-14-08-46/lote_id/2601

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/0599171e-6e4f-4fad-8477-5c0efa397698)

**Comment by Apiraja** [comment]
@scorninpc tem alguma ideia? Tentei até 10 segundos no ajax

**Comment by scorninpc** [comment]
Parece funcionar bem sem o uso do `Delay`, não?

Para pegar o endereço, a gente precisaria implementar aquele :substr  https://github.com/scorninpc/urbanmove.com.br/issues/7

**Comment by scorninpc** [comment]
@Apiraja, atualizei algumas libs e agora roda `xpath 1.0.5` o que inclui o substring

![image](https://github.com/scorninpc/urbanmove.com.br/assets/2607849/20a063b2-fc6b-4074-bbdd-95881b29b95e)


1. recupera o texto da descrição
`//div[contains(@class, 'descricao')]/p/text()`

2. recupera todo o texto DEPOIS de `LOCALIZAÇÃO:`
`substring-after(//div[contains(@class, 'descricao')]/p/text(),'LOCALIZAÇÃO:')`

3. recupera todo o texto ANTES de `–`
`substring-before(substring-after(//div[contains(@class, 'descricao')]/p/text(),'LOCALIZAÇÃO:'),'–')`

**Comment by Apiraja** [comment]
Só pra entender, ele não deveria ter pego o texto "esquina...." até o -

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/2d19294f-6b4d-4c6e-bf88-b68492c27319)


PARTES DOS LOTES 6 E 7, DA QUADRA Nº 125, SITUADO NO LOTEAMENTO DENOMINADO JARDIM OURO BRANCO, DESTA CIDADE, COM A ÁREA DE 428,40 METROS QUADRADOS. CONFRONTAÇÕES: com as divisas e confrontações constantes da MATRÍCULA Nº 21.217 junto ao CARTÓRIO DE REGISTRO DE IMÓVEIS DO 1º OFÍCIO DESTA COMARCA. BENFEITORIAS: Sobre o imóvel existe uma casa edificada em alvenaria, cobertura com telhas de barro, forro em laje, em regular estado, medindo aproximadamente 300,00 Metros quadrados (fotos em anexo)LOCALIZAÇÃO: Rua Manoel Ribas, nº 1817 esquina com Rua Odinot Machado – imediações da Praça dos Pioneiros, próximo ao supermercado cidade canção do ouro branco AVALIAÇÃO: R$1.000.000,00 (UM MILHÃO DE REAIS).

**Comment by scorninpc** [comment]
Ele vai pegar tudo, depois só o azul, depois so o verde

![image](https://github.com/scorninpc/urbanmove.com.br/assets/2607849/d1e7c3b4-bbd5-4572-a490-e6e4675ab891)

> 
> 
>     recupera o texto da descrição
>     //div[contains(@class, 'descricao')]/p/text()
> 
>     recupera todo o texto DEPOIS de LOCALIZAÇÃO:
>     substring-after(//div[contains(@class, 'descricao')]/p/text(),'LOCALIZAÇÃO:')
> 
>     recupera todo o texto ANTES de –
>     substring-before(substring-after(//div[contains(@class, 'descricao')]/p/text(),'LOCALIZAÇÃO:'),'–')
>

**Comment by scorninpc** [comment]
ó, de dentro pra fora, do cinza pro verde

![image](https://github.com/scorninpc/urbanmove.com.br/assets/2607849/f3064b7f-05c3-4d58-9a5a-668677bff234)

`substring-before(TEXTO, TEXTO)`
`substring-after(TEXTO, TEXTO)`

eu coloquei um dentro do outro

`substring-after(   substring-before(TEXTO, TEXTO)   , TEXTO)`
