### ISSUE TITLE
oaleiloes.com.br

### ISSUE THREAD

**Issue by PriscillaSousa** [scorninpc/urbanmove.com.br#15]
-os documentos estão dentro de uma pasta. ‘edital e informações’
consigo pegar o link dos documentos, mas não rodam. Os documentos são do 1 ao 5.
no documento 6 é a 'pasta'.
![Erro84](https://github.com/scorninpc/urbanmove.com.br/assets/137285829/5e61221e-80de-4e1e-8fcd-be2d766eac93)
![erro 84](https://github.com/scorninpc/urbanmove.com.br/assets/137285829/2a46f982-6546-4d00-8f40-ebb744d76a01)

**Comment by Apiraja** [comment]
https://www.oaleiloes.com.br/externo/lote/7663/apartamento-no-109-do-bloco-em-brasilia

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/37e9c2e4-ed4b-4f00-adb0-218a8af694df)

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/dc9580fa-7820-4d26-98db-9d809e4e6487)

Alguma sugestão para buscar o link correto da imagem?

**Comment by scorninpc** [comment]
> Alguma sugestão para buscar o link completo da imagem?

Isso ai precisa ser tratado no backend, vou providenciar
