### ISSUE TITLE
Parent > span retronando valores diferentes

### ISSUE THREAD

**Issue by Apiraja** [scorninpc/urbanmove.com.br#18]
Bruno tem ideia o motivo do retorno ser diferente?

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/bb3e58f1-15d8-491e-868c-1e0ba147f02d)

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/a78d3435-f660-4142-8348-14601fcf9600)

```html
 <li class="card-action-item">
              <div class="card-action-item-content">
                <span class="card-action-item-text ">Data</span>
                <span class="card-action-item-date">
                  21/06/23 às 14h04
                </span>
              </div>
              <span class="card-action-item-value">R$ 136.000,00</span>
          </li>
```

https://www.portalzuk.com.br/imovel/sp/sao-paulo/bras/avenida-alcantara-machado-2978/26961-172938

Estava testando no Teste zuk

**Comment by scorninpc** [comment]
Achei o erro, que ocorre quando usa `>` logo após um `:parent`

Vou resolver e te retorno

**Comment by scorninpc** [comment]
Corrigido, agora funciona igual nos 2 casos

![image](https://github.com/scorninpc/urbanmove.com.br/assets/2607849/70edcf72-7605-4a49-97e4-bb8050238890)
