### ISSUE TITLE
Revisão da documentação

### ISSUE THREAD

**Issue by Apiraja** [scorninpc/urbanmove.com.br#19]
Do que conversamos hoje, o que acho que falta implementar na plataforma é a função contains. O find na plataforma seria apenas dar espaço, correto?!

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/a52d160d-fdbc-4664-b5ba-1535ca3cb55f)

Implementei o que conversamos na documentação, quando fui testar percebi algumas coisas e coloquei como comentário na documentação, se puder confirmar o funcionamento por favor. Um dos itens é o do problema anterior que enviei.

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/3be339e8-3be5-4e41-a229-8e76ac44cd29)

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/6e1c0d46-34c0-4781-bf21-fa0873a044ae)

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/fe678709-4bbb-4d03-b730-0bf80b72f066)

**Comment by scorninpc** [comment]
André, o find é uma função do javascript, ele nao faz parte do seletor. Nesse caso o `find()` é igual `$()`, serve pra mesma coisa, é só costume meu
