### ISSUE TITLE
d1lance.com.br

### ISSUE THREAD

**Issue by scorninpc** [scorninpc/urbanmove.com.br#20]
O site tem proteção contra bots

![image](https://github.com/scorninpc/urbanmove.com.br/assets/2607849/d2c218dc-6276-439d-af5b-bee258b4a176)

**Comment by Apiraja** [comment]
Nesse caso não dá pra fazer um botzinho igual do selenium que clica em cookies, etc...

**Comment by scorninpc** [comment]
O problema não são os cookies. Ele pede para preencher aqueles captcha sabe?

Mas vamos deixar eles em standby por enquanto e partir pro crawler, depois a gente volta nesses casos. Acredito que um proxy vai resolver

**Comment by Apiraja** [comment]
Boa!

**Comment by scorninpc** [comment]
vou deixar aberto, pois ainda não solucionamos blz?
