### ISSUE TITLE
CloudFlare - Proteção contra bots autonomos

### ISSUE THREAD

**Issue by scorninpc** [scorninpc/urbanmove.com.br#21]
@Apiraja, os sites da plataforma `[Sua Plataforma de Leilão | Degrau Publicidade e Internet](https://www.suaplataformadeleilao.com.br/)` todos possuem bloqueio contra bots

identifiquei o `https://www.leilaooficialonline.com.br` e o `https://www.d1lance.com.br`

Perdi 2 dias nisso ja e não consigo achar uma solução

Para eu saber o tamanho do problema, você consegue me dizer, quantos sites você levantou que são desse plataforma?

**Comment by Apiraja** [comment]
Além desses apenas o www.agsleiloes.com.br
Para esses casos podemos estudar uma integração direta com eles ou algo do tipo. Não é um volume relevante.

**Comment by scorninpc** [comment]
Então André, vou deixar esses 3 em standby, o que você acha? porque ja tomou muito tempo , com bastante coisa pra fazer né?

**Comment by Apiraja** [comment]
Melhor...

**Comment by scorninpc** [comment]
Mas vou deixar ele aberto blz? assim a gente sabe que tem coisa pra fazer blz?

**Comment by Apiraja** [comment]
O AMLeiloeiro da Leilotech (empresas de sistemas) também está com o cloudflare

**Comment by Apiraja** [comment]
Alterei o link de busca e houve retorno... Interessante para pelo menos criarmos os seletores

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/b7b54e71-5a45-4982-8827-7802f097d7e4)

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/86f983e4-0278-453a-ba2c-2be7321a2104)

**Comment by TrovilhoJosh** [comment]
https://www.psnleiloes.com.br/ esse site da o mesmo problema

**Comment by Apiraja** [comment]
Lista Nessa árvore:
https://www.destakleiloes.com.br
www.AMLeiloeiro.com.br
www.agsleiloes.com.br
https://www.d1lance.com.br
https://www.leilaooficialonline.com.br

**Comment by TrovilhoJosh** [comment]
www.mgl.com.br

**Comment by scorninpc** [comment]
amleiloeiro.com.br
https://github.com/scorninpc/urbanmove.com.br/issues/9#issuecomment-1636271459

**Comment by scorninpc** [comment]
Pessoal parece que funcionou bem

![image](https://github.com/scorninpc/urbanmove.com.br/assets/2607849/406cfad9-1032-4014-8435-2a4899f08296)

@Apiraja, se puder amanha, com calma, testar alguns, um por um, e a gente validar se funciona, seria otimo. Porque funcionando, ja sei qual caminho seguir

Nesse caso, focar na proteção contra bot beleza?
