### ISSUE TITLE
Agostinho Leilões

### ISSUE THREAD

**Issue by Apiraja** [scorninpc/urbanmove.com.br#22]
@scorninpc, alguma ideia para retornar o número do processo? https://agostinholeiloes.com.br/item/1435/detalhes?page=1

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/7c0c07d2-5e93-4c8a-a7eb-801af3f2e5f0)

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/785910e1-dc2d-4949-8f7a-aba21bf92bcb)

Esse site faz parte do Soleon, é um site que exige o uso de quase tudo, se puder dar uma revisada nele e ver se as variáveis estão no padrão, ai uso de case para passar para o pessoal.

**Comment by Apiraja** [comment]
Depois tenho que criar Agostinho Leilões - Praça Única 
[Agostinho Leilões](https://agostinholeiloes.com.br/item/2194/detalhes?page=1)
Pois alguns parâmetros foram alterados como preço, data e avaliação.
Uma boa prática é sempre finalizar e testar com outro link para ver se realmente o que foi feito está certo e é o suficiente.

**Comment by scorninpc** [comment]
Rapaz, esse site ai é bem completo mesmo em

Uma coisa que poderia facilitar, seria o uso de contents. Por exemplo:

no lugar de usar:

`#content > div:nth-child(2) > div:nth-child(3) > div:nth-child(3) > h6:nth-child(3)`

usar o 

`strong:contains('Valor de Avaliação'):parent`

Acho que ficaria mais simples e mais certeiro não acha?

Agora o numeo do processo, vou precisar pensar em algo pra programar viu!

**Comment by Apiraja** [comment]
Não esquenta agora com o número do processo, achei que pudesse ter uma maneira simples de fazer que eu não soubesse. Depois precisaremos captar vários textos dentro de textos, então podemos incluir esse caso no bolo

**Comment by Apiraja** [comment]
Para pegar esse segundo lance inicial, o strong:contains("Lance Inicial:"):nth-child(2) deveria funcionar? Certo?

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/5e08d1b2-d88c-49c1-beeb-3e86ec05c07f)
 

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/b5916ce1-b33f-4c84-b8ec-2fe058e01fdf)

**Comment by Apiraja** [comment]
ou o strong:contains("Lance Inicial:"):nth-child(2):parent...

**Comment by scorninpc** [comment]
não funciona, pq `nth-child(2)` não pega o segundo item selecionado. ele pega o segundo filho. e não tem 2 `strong` no mesmo `h6`
