### ISSUE TITLE
biasileiloes.com.br

### ISSUE THREAD

**Issue by GabrielAle13** [scorninpc/urbanmove.com.br#26]
https://www.biasileiloes.com.br/

1. Literalmente nada roda.

**Comment by scorninpc** [comment]
Parece que nem o proprio site funciona.

Ao clicar em um lote, pede para fazer esse cadastro:

![image](https://github.com/scorninpc/urbanmove.com.br/assets/2607849/0a856ab3-d888-4a4b-92fc-3ea9557cbee1)

Mas mesmo se cadastrando, continua não abrindo o lote

**Comment by scorninpc** [comment]
Ajustei a pagina de teste das variaveis, agora está funcionando

![Uploading image.png…]()

Mas não fecha esse issue por favor, porque na hora do crawler ele vai dar problema
