### ISSUE TITLE
psnleiloes.com.br

### ISSUE THREAD

**Issue by GabrielAle13** [scorninpc/urbanmove.com.br#27]
https://www.psnleiloes.com.br/detalhe-lote/36763/005/

1. Os links dos documentos não estão disponíveis pra mim.

![image](https://github.com/scorninpc/urbanmove.com.br/assets/112965789/fd5672c5-bea6-460a-922a-c173fdc9e38b)

2. data não está disponível na página dos imovéis, então não tem como pegar.

**Comment by Apiraja** [comment]
Para pegar a Data teremos que futuramente implementar uma rotina que busca a informação na página principal dos leilões e não dos lotes

**Comment by Apiraja** [comment]
Não é prioridade

**Comment by Apiraja** [comment]
e o link creio que seja uma solução para ajax

**Comment by Apiraja** [comment]
desmembrado em dois issues
