### ISSUE TITLE
judhastas.com.br

### ISSUE THREAD

**Issue by GabrielAle13** [scorninpc/urbanmove.com.br#28]
1. Visitas está preso com um texto de uma div

![image](https://github.com/scorninpc/urbanmove.com.br/assets/112965789/4da8485e-83bf-4dd8-9685-08d9919b2726)

2. Comitente está preso com o resto da descrição

![image](https://github.com/scorninpc/urbanmove.com.br/assets/112965789/666ceb33-7dab-420e-aa5b-43bf1050a5da)

**Comment by Apiraja** [comment]
Para visitas teremos que utilizar o xpath

Comitente pode usar: 
![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/4256207f-18d3-4865-a171-7bc80a01dd1e)

**Comment by Apiraja** [comment]
Comitente resolvido

Visitas não resolvido, não funcionou.

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/5e13e24b-8c88-4e7d-a7bd-28b1e3696f29)

'''html
<div class="col-12 col-lg-3"> 
<svg class="svg-inline--fa fa-eye fa-w-18" </svg>

 Visitas: 179<br><br> 
<strong>Processo: </strong><span>0135600-03.2005.5.02.0045</span><br><strong>Exequente: </strong><span>Ricardo de Ávila Costa Tacioli, CPF: 266.001.688-70</span><br><strong>Executado: </strong><span>Datas do Brasil Ltda, CNPJ: 74.226.127/0001-60; Gildasio Cardoso Mendes, CPF: 410.141.707-53; Marinalva Lopes dos Santos Mendes, CPF: 882.773.808-87</span></div>
'''

**Comment by Apiraja** [comment]
A palavra Visitas não retorna no xpath nem no console nem no nosso sistema

**Comment by Apiraja** [comment]
![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/a9abade7-94a6-457c-8d43-034cf04250c6)
substring-before(substring-after(//div[.//strong[contains(text(), "Processo:")]], "Visitas:"), "P")
resolvido
