### ISSUE TITLE
https://www.grupolance.com.br/

### ISSUE THREAD

**Issue by TrovilhoJosh** [scorninpc/urbanmove.com.br#34]
https://www.grupolance.com.br/

https://www.grupolance.com.br/imoveis/imoveis-comerciais/rj/rio-de-janeiro/imovel-com-tres-predios-instituicao-de-ensino-area-total-de-5300m2-realengo-rio-de-janeiro-rj-20955#foto-2

Data 02
'substring-before(//*[contains(text(), 'Encerramento 2ª Praça')]/strong/text(),'às')' era para retornar a data, porem não possui retorno

Preço 02
'substring-after(//*[contains(text(), 'Encerramento 2ª Praça')]/div/text(), 'R$')' era para retornar o valor da segunda Praça, porem não retorna nada.

**Comment by Apiraja** [comment]
Realmente é estranho, mas uma excelente solução é utilizar a class desse box, a .card-defasagem, ai vai pro pai dela e pega os elementos.

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/0e5bf954-48df-4ae4-aba9-db313a103dbb)

Referente ao primeiro leilão, eu alterei o texto que estava buscando, apenas para encerramento, ai ele pega os que são leilão único.
![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/9ace28f1-e186-4b00-ae2f-c52fc22494f9)

**Comment by Apiraja** [comment]
![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/a224e83e-5c32-41e7-ab97-e344ca9c10a6)
Já implementei
