### ISSUE TITLE
Exemplos de erros Paginação

### ISSUE THREAD

**Issue by Apiraja** [scorninpc/urbanmove.com.br#59]
https://ssl1.visar.com.br/octaviovianna.lel.br/Principal.asp

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/4b8f641b-7faf-4911-9d47-e129840b21e6)

https://www.lelialenz.com.br/home/

![image](https://github.com/scorninpc/urbanmove.com.br/assets/137231287/58469799-5670-44bc-9f52-45cbdf79f0e4)

**Comment by scorninpc** [comment]
Esse exemplo um caso que não usa url, não tem site map, então acho que poderia usar o google

https://www.google.com/search?client=firefox-b-d&q=site%3Ahttps%3A%2F%2Fssl1.visar.com.br+inurl%3ALeilao.asp

**Comment by Apiraja** [comment]
https://www.milanleiloes.com.br/Leiloes/Agenda.asp

<div class="caixa-1de4 cursorLink" onclick="AbrirPagLeilao(12008, 'catalogo', '', '');">
https://www.milanleiloes.com.br/Leiloes/Catalogo.asp?IdLeilao=12008
	

onclick="AbrirPagLeilao(11917, 'especifica', 'ExtraJudicial/Judicial.asp?CL=[CodLeilao]', '');"
https://www.milanleiloes.com.br/Editais/ExtraJudicial/Judicial.asp?CL=11917


AbrirPagLeilao(12057, 'especifica', 'ExtraJudicial/Bradesco.asp?CL=[CodLeilao]', '');
https://www.milanleiloes.com.br/Editais/ExtraJudicial/Bradesco.asp?CL=12057
