### ISSUE TITLE
:substr

### ISSUE THREAD

**Issue by scorninpc** [scorninpc/urbanmove.com.br#7]
ajudaria muito na extração de informações

`:substr(inicio, fim)` retornaria um pedaço da string

**Comment by Apiraja** [comment]
Quando houver demanda iremos utilizar o substr no xpath

https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/substring

**Comment by scorninpc** [comment]
> Quando houver demanda iremos utilizar o substr no xpath
> 
> https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/substring

essas funções não funcionam

![image](https://github.com/scorninpc/urbanmove.com.br/assets/2607849/2416ee7f-50ce-49dd-80d4-4b2cb119b30d)
